### PR TITLE
add arthur york bio and demo hours

### PR DESCRIPTION
**Pull request by ahyork**

### CODE REVIEW

**Review by wkiri — CHANGES_REQUESTED** [review]
Thank you, Arthur!

Please add arthur.jpg to your commit (in TABios/pics/) and we'll be good to go!

**Comment by wkiri** [comment]
One other request - please insert your bio alphabetically (by last name) on the TA list.  Thanks!

**Comment by ahyork** [comment]
I just swapped the position of my ta bio to be in alphabetical order. I also added my office hours and uploaded my picture

**Comment by wkiri** [comment]
Looks great, thank you!

**Pull request merged**
